// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC57rKjFdO0XPSg5V4ng1D8hpTdeMhvKgE',
    appId: '1:1040582010578:web:9972b537a76041a1c02f0b',
    messagingSenderId: '1040582010578',
    projectId: 'news-app-f4768',
    authDomain: 'news-app-f4768.firebaseapp.com',
    storageBucket: 'news-app-f4768.appspot.com',
    measurementId: 'G-9RQWC1ZJ21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_sYybukSSE5tD_q73k4lcpgLL6H3g2PE',
    appId: '1:1040582010578:android:1caccae3989a30a3c02f0b',
    messagingSenderId: '1040582010578',
    projectId: 'news-app-f4768',
    storageBucket: 'news-app-f4768.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAznr3ILQL7Eh_YOehyYSDM_0ie4WLOh_I',
    appId: '1:1040582010578:ios:a46b71ebc8b49306c02f0b',
    messagingSenderId: '1040582010578',
    projectId: 'news-app-f4768',
    storageBucket: 'news-app-f4768.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAznr3ILQL7Eh_YOehyYSDM_0ie4WLOh_I',
    appId: '1:1040582010578:ios:a46b71ebc8b49306c02f0b',
    messagingSenderId: '1040582010578',
    projectId: 'news-app-f4768',
    storageBucket: 'news-app-f4768.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC57rKjFdO0XPSg5V4ng1D8hpTdeMhvKgE',
    appId: '1:1040582010578:web:c691465f65fab891c02f0b',
    messagingSenderId: '1040582010578',
    projectId: 'news-app-f4768',
    authDomain: 'news-app-f4768.firebaseapp.com',
    storageBucket: 'news-app-f4768.appspot.com',
    measurementId: 'G-YGNJ7FZ9JD',
  );
}
